language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - rbx
  - jruby-9.1.16.0
jdk:
  - openjdk7
script: bundle exec rake test
env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid
gemfile:
  - Gemfile
  - gemfiles/Gemfile.devise-4.0
  - gemfiles/Gemfile.devise-4.1
  - gemfiles/Gemfile.rails-4.2
install: "travis_retry bundle install"
services:
  - mongodb
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/Gemfile.devise-4.0
    - rvm: 2.4.3
      gemfile: gemfiles/Gemfile.devise-4.1
    - rvm: 2.5.0
      gemfile: gemfiles/Gemfile.devise-4.0
    - rvm: 2.5.0
      gemfile: gemfiles/Gemfile.devise-4.1
  include:
    - rvm: 2.5.0
      gemfile: gemfiles/Gemfile.rails-master
      env: DEVISE_ORM=active_record
    - rvm: 2.5.0
      gemfile: gemfiles/Gemfile.rails-master
      env: DEVISE_ORM=mongoid
  allow_failures:
    - rvm: rbx
    - rvm: jruby-9.1.16.0
      gemfile: Gemfile
    - gemfile: gemfiles/Gemfile.rails-master
