language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
script: bundle exec rake test
env:
  - DEVISE_ORM=active_record
  - DEVISE_ORM=mongoid
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - Gemfile
install: "travis_retry bundle install"
services:
  - mongodb
matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-3.2.x
      env: DEVISE_ORM=active_record
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-3.2.x
      env: DEVISE_ORM=mongoid
