dist: xenial
language: ruby
sudo: false

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head

script: bundle exec rake test

env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.0
  - gemfiles/Gemfile.rails-5.1
  #- gemfiles/Gemfile.rails-5.2
  - gemfiles/Gemfile.rails-master

install: travis_retry bundle install

services:
  - mongodb

matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile.rails-master
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/Gemfile.rails-master
