language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
  - rbx-2
#  - rbx-3
  - jruby-9.0.5.0
script: bundle exec rake test
env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid
gemfile:
  - Gemfile
  - gemfiles/Gemfile.r42.devise-3.5
  - gemfiles/Gemfile.r40.devise-3.5
install: "travis_retry bundle install"
services:
  - mongodb
matrix:
  include:
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.r32
      env: DEVISE_ORM=active_record
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.r32
      env: DEVISE_ORM=mongoid
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.r4.devise-3.2
      env: DEVISE_ORM=active_record
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.r4.devise-3.2
      env: DEVISE_ORM=mongoid
  exclude:
     - rvm: 2.1
     - rvm: 2.2
     - rvm: rbx-2
#    - rvm: jruby-19mode
#      gemfile: gemfiles/Gemfile.rails-3.2.x
#      env: DEVISE_ORM=mongoid
