language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - jruby-18mode
script: rake test
env:
  - DEVISE_ORM=active_record
  - DEVISE_ORM=mongoid
matrix:
  allow_failures:
    - rvm: jruby
